#views.py
from django.shortcuts import render
from rest_framework.decorators import  api_view
from rest_framework.response import Response
from .models import Tickets
from .serializer import TicketSerializer
from rest_framework.pagination import PageNumberPagination
from rest_framework.permissions import IsAuthenticated
from rest_framework.decorators import permission_classes
from django.views.decorators.cache import cache_page
# from django_filters.rest_framework import DjangoFilterBackend
# Create your views here.
@api_view(['GET','POST'])
@cache_page(60)
@permission_classes([IsAuthenticated])
def ticket_list(request):
    if request.method == 'GET':
        ordering = request.query_params.get("ordering")
        search = request.query_params.get("search")     #ordering
        tickets = Tickets.objects.all()
        category = request.query_params.get("category")
        title = request.query_params.get("title")
        if category:                                         #Filter
            tickets = Tickets.filter(category = category)
        if title:
            tickets = Tickets.filter(title_icontains = title)  #_icontains means no charecter sensitive

        if ordering:
            tickets = Tickets.order_by(ordering)        #ordering
            serializer=TicketSerializer(tickets,many=True)

        paginator = PageNumberPagination()
        paginator.page_size = 2         #same as settings
        paginator_tickets = paginator.paginate_queryset(tickets , request)
        serializer=TicketSerializer(paginator_tickets,many=True)
        return paginator.get_paginated_response(serializer.data)
    if request.method == 'POST':
        serializer=TicketSerializer(data=request.data)  
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data,status=201)
        return Response(serializer.error,status=400)
    
@api_view(['GET','PUT','DELETE','PATCH'])
@cache_page(60)
@permission_classes([IsAuthenticated])
def ticket_details(request,id):
    try:
        ticket = Tickets.objects.get(id=id)
    except Tickets.DoesNotExist:
        return Response({'error':'Not found'},status=404)
    if request.method == 'GET':
        serializer = TicketSerializer(ticket)
        return Response(serializer.data)
    if request.method == 'PUT':
        serializer = TicketSerializer(ticket,data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.error,status=400)
    if request.method == 'DELETE':
        ticket.delete()
        return Response({'Student':'Deleted'})
    if request.method == 'PATCH':
        serializer = TicketSerializer(ticket,data=request.data,partial=True)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.error,status=400)
   


#models.py
from django.db import models


# Create your models here.
class Tickets(models.Model):
    title=models.CharField(max_length=100)
    description = models.TextField
    category = models.CharField(max_length=20)
    priority = models.CharField(max_length=20)

    def __str__(self):
        return self.title


#settings.py
"""
Django settings for complaints project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f#xmo7%w)qpeq*nt+_he7)hjtgfnq3n6)fnne=h790%fd1go^v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'student',
    'rest_framework'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'complaints.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'complaints.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'query',
        'USER':'postgres',
        'PASSWORD':'root',
        'HOST':'localhost',
        'PORT':'5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
REST_FRAMEWORK = { 
    "DEFAULT_PAGINATION_CLASS":
        "rest_framework.pagination.PageNumberPagination",    #adding pagination

    "PAGE_SIZE" : 2, 
    "DEFAULT_FILTER_BACKENDS" :[                    #adding Filters 
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",             #adding order
    ],

   
}
REST_FRAMEWORK={
     "DEFAULT_AUTHENTICATION_CLASSES" : (
        "rest_framework.authentication.SessionAuthentication",  # allows admin login
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}

#urls.py
"""
URL configuration for complaints project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/6.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path
from student.views import ticket_list
from student.views import ticket_details
from rest_framework_simplejwt.views import(TokenObtainPairView, TokenRefreshView)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('tickets/',ticket_list),
    path('tickets/<int:id>/',ticket_details),

    path("api/token/",TokenObtainPairView.as_view()),        #this is for login
    path("api/Token/refresh/" , TokenRefreshView.as_view()),       #this is for get new token
    #.as_view converts the class into function
]

#serielizer.py
from rest_framework import serializers
from .models import Tickets
class TicketSerializer(serializers.ModelSerializer):
    class Meta:
        model = Tickets
        fields = '__all__'
